config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/admin/project_pop_up' => 'admin/projects#pop_up_view'
  get '/admin/get_team' => 'admin/organization_charts#get_users'
  get '/admin/user_detail' => 'admin/organization_charts#user_detail'
  match '/admin/api/get_formated_value' => 'admin/dashboard#return_formated_value', via: [:get]

  match '/admin/api/tester' => 'admin/projects#tester', via: [:get]
  

  match '/admin/api/restore_role', to: 'admin/roles#restore', via: [:post]
  match '/admin/api/restore_admin_user', to: 'admin/admin_users#restore', via: [:post]
  match '/admin/api/restore_admin_users_audit', to: 'admin/admin_users_audits#restore', via: [:post]
  match '/admin/api/restore_lookup_type', to: 'admin/lookup_types#restore', via: [:post]
  match '/admin/api/restore_lookup', to: 'admin/lookups#restore', via: [:post]
  match '/admin/api/restore_vacation_policy', to: 'admin/vacation_policies#restore', via: [:post]
  match '/admin/api/restore_holiday_calendar', to: 'admin/holiday_calendars#restore', via: [:post]
  match '/admin/api/restore_project_type', to: 'admin/project_types#restore', via: [:post]
  match '/admin/api/restore_resource', to: 'admin/resources#restore', via: [:post]
  match '/admin/api/restore_overhead', to: 'admin/overheads#restore', via: [:post]
  match '/admin/api/restore_client', to: 'admin/clients#restore', via: [:post]
  match '/admin/api/restore_vacation', to: 'admin/vacations#restore', via: [:post]
  match '/admin/api/restore_timesheet', to: 'admin/timesheets#restore', via: [:post]
  match '/admin/api/restore_project', to: 'admin/projects#restore', via: [:post]
  match '/admin/api/restore_assigned_resource', to: 'admin/assigned_resources#restore', via: [:post]
  match '/admin/api/restore_project_overhead', to: 'admin/project_overheads#restore', via: [:post]
  match '/admin/api/restore_delivery_milestone', to: 'admin/delivery_milestones#restore', via: [:post]
  match '/admin/api/restore_delivery_invoicing_milestone', to: 'admin/delivery_invoicing_milestones#restore', via: [:post]
  match '/admin/api/restore_invoicing_milestone', to: 'admin/invoicing_milestones#restore', via: [:post]
  match '/admin/api/restore_invoicing_delivery_milestone', to: 'admin/invoicing_delivery_milestones#restore', via: [:post]
  match '/admin/api/restore_pipeline', to: 'admin/pipelines#restore', via: [:post]
  match '/admin/api/restore_staffing_requirement', to: 'admin/staffing_requirements#restore', via: [:post]
  match '/admin/api/restore_invoice_header', to: 'admin/invoice_headers#restore', via: [:post]
  match '/admin/api/restore_invoice_line', to: 'admin/invoice_lines#restore', via: [:post]
  match '/admin/api/restore_payment_header', to: 'admin/payment_headers#restore', via: [:post]
  match '/admin/api/restore_payment_line', to: 'admin/payment_lines#restore', via: [:post]

  match '/admin/api/project_type_description' => 'admin/project_types#description_for_lookup', via: [:get]
  match '/admin/api/vacation_policy_description' => 'admin/vacation_policies#description_for_lookup', via: [:get]
  match '/admin/api/skill_for_staffing' => 'admin/assigned_resources#skill_for_staffing', via: [:get]
  match '/admin/api/designation_for_staffing' => 'admin/assigned_resources#designation_for_staffing', via: [:get]
  match '/admin/api/start_date_for_staffing' => 'admin/assigned_resources#start_date_for_staffing', via: [:get]
  match '/admin/api/end_date_for_staffing' => 'admin/assigned_resources#end_date_for_staffing', via: [:get]
  match '/admin/api/hours_per_day_for_staffing' => 'admin/assigned_resources#hours_per_day_for_staffing', via: [:get]
  match '/admin/api/convert_pipeline', to: 'admin/pipelines#convert_pipeline', via: [:post]
  match '/admin/api/resources_for_staffing' => 'admin/resources#resources_for_staffing', via: [:get]
  match '/admin/api/resource_details' => 'admin/resources#resource_details', via: [:get]
  match '/admin/api/staffing_fulfilled', to: 'admin/assigned_resources#staffing_fulfilled', via: [:post]
  match '/admin/api/invoicing_milestones_for_project' => 'admin/invoicing_milestones#invoicing_milestones_for_project', via: [:get]
  match '/admin/api/invoicing_milestone' => 'admin/invoice_lines#invoicing_milestone', via: [:get]
  match '/admin/api/invoicing_milestone_uninvoiced' => 'admin/invoice_lines#invoicing_milestone_uninvoiced', via: [:get]
  match '/admin/api/invoice_adder_type' => 'admin/invoice_lines#invoice_adder_type', via: [:get]
  match '/admin/api/invoice_line_narrative' => 'admin/invoice_lines#invoice_line_narrative', via: [:get]
  match '/admin/api/unpaid_amount' => 'admin/invoice_lines#unpaid_amount', via: [:get]
  match '/admin/api/invoice_lines_for_header' => 'admin/invoice_lines#invoice_lines_for_header', via: [:get]
  match '/admin/api/approve_vacation', to: 'admin/vacations#approve_vacation', via: [:post]
  match '/admin/api/reject_vacation', to: 'admin/vacations#reject_vacation', via: [:post]
  match '/admin/api/cancel_vacation', to: 'admin/vacations#cancel_vacation', via: [:post]
  match '/admin/api/make_vacation_pending', to: 'admin/vacations#make_vacation_pending', via: [:post]
  match '/admin/api/approve_timesheet', to: 'admin/timesheets#approve_timesheet', via: [:post]
  match '/admin/api/reject_timesheet', to: 'admin/timesheets#reject_timesheet', via: [:post]
  match '/admin/api/cancel_timesheet', to: 'admin/timesheets#cancel_timesheet', via: [:post]
  match '/admin/api/make_timesheet_pending', to: 'admin/timesheets#make_timesheet_pending', via: [:post]
  match '/admin/api/clients_for_business_unit' => 'admin/pipelines#clients_for_business_unit', via: [:get]

  match '/admin/api/admin_user_details' => 'admin/admin_users#admin_user_details', via: [:get]
  match '/admin/api/overall_delivery_health' => 'admin/projects#overall_delivery_health', via: [:get]
  match '/admin/api/project_details' => 'admin/projects#project_details', via: [:get]
  match '/admin/api/missed_delivery' => 'admin/projects#missed_delivery', via: [:get]
  match '/admin/api/missed_invoicing' => 'admin/projects#missed_invoicing', via: [:get]
  match '/admin/api/missed_payments' => 'admin/projects#missed_payments', via: [:get]
  match '/admin/api/direct_resource_cost' => 'admin/projects#direct_resource_cost', via: [:get]
  match '/admin/api/direct_overhead_cost' => 'admin/projects#direct_overhead_cost', via: [:get]
  match '/admin/api/total_direct_cost' => 'admin/projects#total_direct_cost', via: [:get]
  match '/admin/api/total_indirect_resource_cost_share' => 'admin/projects#total_indirect_resource_cost_share', via: [:get]
  match '/admin/api/total_indirect_overhead_cost_share' => 'admin/projects#total_indirect_overhead_cost_share', via: [:get]
  match '/admin/api/total_indirect_cost_share' => 'admin/projects#total_indirect_cost_share', via: [:get]
  match '/admin/api/total_cost' => 'admin/projects#total_cost', via: [:get]
  match '/admin/api/total_revenue' => 'admin/projects#total_revenue', via: [:get]
  match '/admin/api/contribution' => 'admin/projects#contribution', via: [:get]
  match '/admin/api/contribution_details' => 'admin/projects#contribution_details', via: [:get]
  match '/admin/api/gross_profit' => 'admin/projects#gross_profit', via: [:get]
  match '/admin/api/gross_profit_details' => 'admin/projects#gross_profit_details', via: [:get]
  match '/admin/api/delivery_health' => 'admin/projects#delivery_health', via: [:get]
  match '/admin/api/pipeline_for_status' => 'admin/pipelines#pipeline_for_status', via: [:get]
  match '/admin/api/pipeline_for_all_statuses' => 'admin/pipelines#pipeline_for_all_statuses', via: [:get]
  match '/admin/api/resource_distribution_combos' => 'admin/resources#resource_distribution_combos', via: [:get]
  match '/admin/api/resource_details' => 'admin/resources#resource_details', via: [:get]
  match '/admin/api/staffing_forecast' => 'admin/staffing_requirements#staffing_forecast', via: [:get]
  match '/admin/api/staffing_required' => 'admin/staffing_requirements#staffing_required', via: [:get]
  match '/admin/api/staffing_fulfilled' => 'admin/staffing_requirements#staffing_fulfilled', via: [:get]
  match '/admin/api/deployable_resources' => 'admin/staffing_requirements#deployable_resources', via: [:get]
  match '/admin/api/resource_efficiency' => 'admin/admin_users#resource_efficiency', via: [:get]
  match '/admin/api/business_unit_efficiency' => 'admin/admin_users#business_unit_efficiency', via: [:get]
  match '/admin/api/overall_efficiency' => 'admin/admin_users#overall_efficiency', via: [:get]
  match '/admin/api/active_users_outflow' => 'admin/admin_users_audits#active_users_outflow', via: [:get]
  match '/admin/api/inactive_users_outflow' => 'admin/admin_users_audits#inactive_users_outflow', via: [:get]
  match '/admin/api/all_users_outflow' => 'admin/admin_users_audits#all_users_outflow', via: [:get]
  match '/admin/api/active_users_inflow' => 'admin/admin_users_audits#active_users_inflow', via: [:get]
  match '/admin/api/inactive_users_inflow' => 'admin/admin_users_audits#inactive_users_inflow', via: [:get]
  match '/admin/api/all_users_inflow' => 'admin/admin_users_audits#all_users_inflow', via: [:get]
  match '/admin/api/active_users_netflow' => 'admin/admin_users_audits#active_users_netflow', via: [:get]
  match '/admin/api/inactive_users_netflow' => 'admin/admin_users_audits#inactive_users_netflow', via: [:get]
  match '/admin/api/all_users_netflow' => 'admin/admin_users_audits#all_users_netflow', via: [:get]
  match '/admin/api/delivery_milestones' => 'admin/delivery_milestones#delivery_milestones', via: [:get]
  match '/admin/api/delivery_milestone_details' => 'admin/delivery_milestones#delivery_milestone_details', via: [:get]
  match '/admin/api/invoicing_milestones' => 'admin/invoicing_milestones#invoicing_milestones', via: [:get]
  match '/admin/api/invoicing_milestone_details' => 'admin/invoicing_milestones#invoicing_milestone_details', via: [:get]

app/views/admin/organization_charts/_organization_chart.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="../img/logo.ico">
    <link rel="stylesheet" href="https://cdn.rawgit.com/FortAwesome/Font-Awesome/master/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://dabeng.github.io/OrgChart/css/jquery.orgchart.css">
    <link rel="stylesheet" href="http://dabeng.github.io/OrgChart/css/style.css">
    <script type="text/javascript" src="https://cdn.rawgit.com/niklasvh/html2canvas/master/dist/html2canvas.min.js"></script>

</head>
<body>

  <div id="chart-container"><span class="chart_expander expand" title="Expand All"><i class="fa fa-expand" aria-hidden="true" style="font-size: x-large;float: left;"></i></span>
<span class="chart_expander collapse" hidden title="Collapse All"><i class="fa fa-compress" aria-hidden="true" style="font-size: x-large;float: left;"></i></span></div>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.rawgit.com/jakerella/jquery-mockjax/master/dist/jquery.mockjax.min.js"></script>
  <script type="text/javascript" src="http://dabeng.github.io/OrgChart/js/jquery.orgchart.js"></script>
  <!-- <script type="text/javascript" src="http://dabeng.github.io/OrgChart/ondemand-loading-data/scripts.js"></script> -->
  </body>
</html>
<style type="text/css">
.chart_expander{
    margin-left: 20px;
    margin-top: 12px;
    float: left;}
    .table {
      width: 100%;
      max-width: 100%;
      margin-bottom: 20px;
  }
  table {
      background-color: transparent;
  }
  table {
      border-spacing: 0;
      border-collapse: collapse;
  }

  .table-striped>tbody>tr:nth-of-type(odd) {
      background-color: #E2E2E2;
  }
  .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
      padding: 10px;
      line-height: 1.42857143;
      vertical-align: top;
      border-top: 1px solid #ddd;
  }
  .table .table-row-header {
    background:#636363 !important;
    color:#FFF;
  }
  td, th {
      padding: 0;
  }
  .table th , .table td{
      font-size: 12px;
  }
  .table th {
    font-weight: 700;
  }
   #title_bar{
    padding: 0px;
    padding-left: 10px;
  }
  .oc-export-btn{
    /*top: 422px !important;*/
        float: left !important;
        margin-left: 10px;
    position: inherit;
  }
</style>
<script type="text/javascript">
 $.ajax({
            async: false,
            url: "/admin/get_team?id="+'<%=current_admin_user.id%>',
              dataType: 'json',
            success: function (data) {
               datasource =  data;
            }
        })
$('#chart-container').orgchart({
  'data' : datasource,
  'depth': 2,
  'nodeContent': 'title'
});
$(".node").on('click',function(e){
  $(".popup").show()
  popup_view()
  responce  = ajax_call("/admin/user_detail?id="+$(this).attr('id'))
  var html_value = "<span id='close' style='cursor:pointer' hidden></span>"
  value1 = Object.assign(responce, responce["admin_user_details"]);
             html_value = html_value + convert_ajax_to_htm(value1)
             $(".ajax_content").html(html_value)
            $(".admin_user_details,.created_at,.updated_at,.deleted_at,.role_id,.business_unit_id,.department_id,.designation_id,.ip_address,.id,.manager_id,.bill_rate,.cost_rate,.comments,.updated_by,.associate_no,.active,.date_of_leaving").hide()
             $(".modal-header").append("<span class= 'hiddding_header'style='font-family: fantasy;font-size: 20px;align-self: center;margin-top: 900px;margin-left: 460px;'>"+$(this).find(".title").html()+"</span>")
    $("ajax_content").find("td.business_unit")
    $(".hiddding_header,.business_unit,.designation,.name").hide()
    $(".hiddding_header").last().find(".fa").remove()
    $(".hiddding_header").last().show()
})
function popup_view(){
    $('[data-popup-close]').on('click', function(e)  {
        var targeted_popup_class = jQuery(this).attr('data-popup-close');
        $('[data-popup="' + targeted_popup_class + '"]').fadeOut(10);
        $(".dropdown_menu").toggle()
        e.preventDefault();
    });
  }
        function return_only_t_data(responce){
             var ajax_content_value = "</tr><tr>"
             $.each(responce, function(key, value) {
              value = (value == null) ? "" : value
                  ajax_content_value +="<td class='"+key.replace(" ", "_")+"'style = 'border: 1px solid #ddd;' >"+value+"</td>" 
                  });
           ajax_content_value +="</tr>"
           return ajax_content_value
          }

          function convert_ajax_to_htm(responce){
   var ajax_content_value = "<table class = 'table table-striped'><tr class ='table-row-header'>"
           $.each(responce, function(key, value) {
                  ajax_content_value +="<th class='"+key.replace(" ", "_")+" 'style = 'border: 1px solid #ddd;'>"+key.replace(/_/g," ").toUpperCase()+"</th>" 
                  });
           ajax_content_value += "</tr><tr>"
             $.each(responce, function(key, value) {
              value = (value == null) ? "" : value
                  ajax_content_value +="<td class='"+key.replace(" ", "_")+"'style = 'border: 1px solid #ddd;' >"+value+"</td>" 
                  });
           ajax_content_value +="</tr></table>"
           return ajax_content_value
          }

  function ajax_call(url) {
      var responce = ""
   $.ajax({
          async: false,
          url: url,
            dataType: 'json',
          success: function (data) {
             responce =  data;
          }
      })
   return responce;
  }
  $(document).ready(function() {
$("#page_title").html("Organization Chart")
$(".pagination_information,.pagination,.breadcrumb").hide()})
  $(".chart_expander").on('click',function(){
    $(".chart_expander").toggle()
    $(".orgchart").remove()
    if( (jQuery.inArray("expand",$(this).attr('class').split(" ")))== 1){
    $('#chart-container').orgchart({
  'data' : datasource,
  'nodeContent': 'title',
  'exportButton': true,
  'exportFilename': 'MyOrgChart',
  'exportFileextension': 'pdf'
});
    $(".oc-export-btn").css('top', 'auto')
    
    }
    else{
      $(".oc-export-btn").remove()
      $('#chart-container').orgchart({
  'data' : datasource,
  'depth': 2,
  'nodeContent': 'title'
});
    }
    $(".spinner").hide()
    $(".node").on('click',function(e){
  $(".popup").show()
  popup_view()
  responce  = ajax_call("/admin/user_detail?id="+$(this).attr('id'))
  var html_value = "<span id='close' style='cursor:pointer' hidden></span>"
  value1 = Object.assign(responce, responce["admin_user_details"]);
             html_value = html_value + convert_ajax_to_htm(value1)
             $(".ajax_content").html(html_value)
             $(".admin_user_details,.created_at,.updated_at,.deleted_at,.role_id,.business_unit_id,.department_id,.designation_id,.ip_address,.id,.manager_id,.bill_rate,.cost_rate,.comments,.updated_by,.associate_no").hide()
             $(".modal-header").append("<span class= 'hiddding_header'style='font-family: fantasy;font-size: 20px;align-self: center;margin-top: 900px;margin-left: 460px;'>"+$(this).find(".title").html()+"</span>")
    $("ajax_content").find("td.business_unit")
    $(".hiddding_header,.business_unit,.designation,.name").hide()
    $(".hiddding_header").last().find(".fa").remove()
    $(".hiddding_header").last().show()
})
    $(".orgchart").css("display","flex")
$(".orgchart").css('background-size','0')
$("#chart-container").css("border",'.2px dotted #aaa')
$("#chart-container").css("height",'100%')
  })
$(".orgchart").css("display","flex")
$(".orgchart").css('background-size','0')
$("#chart-container").css("border",'.2px dotted #aaa')
$("#chart-container").css("height",'100%')
$("#chart-container").css("overflow",'hidden')

$(".title").attr("title","Click For More Details")
// $(".orgchart").first().hide()
</script>